name: Maven Build and Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Define a list of Operating Systems to run on
        os: [ubuntu-latest, windows-latest]       
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn clean package
